@startuml

class Document {
}

class Element {
}

class Attribute {
    String value
}

abstract class NamedElement {
    String name
}

Document "rootElement" o-- Element
Element o-- "*" Element

Element *-- "*" Attribute

Element --|> NamedElement
Attribute --|> NamedElement
@enduml